### ISSUE TITLE
Virtual Holographic Nodal Platform

### ISSUE THREAD

**Issue by kriskowal** [pinf/genesis.pinf.org#4]
None of these words communicate. I suspect each of them would require a paragraph of explanation.

Perhaps you mean:

> Tool(s) for sharing software development workflows that involve flexible dependency management and the orchestration of virtual machines.

**Comment by kriskowal** [comment]
Breaking this down:
- "platform" is a very abstract notion, a something that other somethings stand on. Clarify both something and something.
- "virtual" is a modifier of "platform", meaning we now have somethings, somethings, and virtual somethings.
- "holographic" can only be an attempt to coin a metaphor in this context. For the metaphor to work, there has to be a something in the optical sense that corresponds corresponds something in this new sense.
- "nodal" is another coined term. Seemingly means "having nodes" and a thing that has nodes is usually called a "graph". Graphs are also a very abstract term. Perhaps you mean a social graph, where each node corresponds to a person. It should be clear that nodes are people and that the people are specific kinds of people like "software developers". Perhaps you mean a "network", where each node is a machine (or a virtual machine). Perhaps you mean a network of instantiations of the platform something. In this case, you might mean "shareable", "distributable", "replicatable", "clonable".

Your opening words need to clarify, not confuse. Coinage is expensive, but you can follow up with that if you _and your audience_ have time to write or read an explanation.

**Comment by kriskowal** [comment]
- "system" is also abstract
- "abstract" is superfluous with all the other highly abstract terms
- "system-wide event loop" probably means "workflow"

**Comment by kriskowal** [comment]
- "event-loop" has a very specific technical meaning in the exact same context, so I would avoid using it as a metaphor for anything.

**Comment by kriskowal** [comment]
- "boot sequence" also has a very specific technical meaning, "a self-managed (autonomous) process of going from an inert state to a living state, as in booting a computer". This isn’t a good term for setting up a developer environment for a project because it explicitly requires a sequence of user actions. This is commonly called "developer environment activation", as you know from "activate", a name we borrowed from Python’s VirtualEnv.

**Comment by cadorn** [comment]
@kriskowal You make lots of good points. This helps a lot. Thanks!

I am realizing that this diagram and the concepts addressed are too abstract at this stage and belong somewhere else as I don't have the depth in docs and implementation to back up the coined terms. They are all used for a reason and meant to inspire and open thinking, not confuse. I will refine this big-picture overview based on your comments for review at a later time. The big-picture is less important right now.

I will replace the overview with one based purely on the technical primitives that PINF.Genesis implements and introduce the above big-picture along with developer companion which is an implemented toolset to move us towards this pig picture overview.

This will make PINF.Genesis completely concrete and minimal as implemented today and leave the future and prototype stuff to developer companion.

**Comment by cadorn** [comment]
The overview presented here will move to devcomp.org . See: https://github.com/devcomp/devcomp.org/issues/1

A new overview will be created based on: https://github.com/pinf/genesis.pinf.org/issues/5
